name: Deploy

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE: ghcr.io/itsdiy0/bouldy-api
  FRONTEND_IMAGE: ghcr.io/itsdiy0/bouldy-frontend

jobs:
  build-backend:
    name: Build & Push API
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.BACKEND_IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest

      - uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-frontend:
    name: Build & Push Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.FRONTEND_IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest

      - uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_API_URL=https://bouldy.diy0.dev

  deploy:
    name: Deploy to K3s
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to homelab
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOMELAB_HOST }}
          username: ${{ secrets.HOMELAB_USER }}
          key: ${{ secrets.HOMELAB_SSH_KEY }}
          script: |
            # Pull latest images
            sudo crictl pull ${{ env.BACKEND_IMAGE }}:latest
            sudo crictl pull ${{ env.FRONTEND_IMAGE }}:latest

            # Restart deployments to pick up new images
            kubectl rollout restart deployment/api -n bouldy
            kubectl rollout restart deployment/frontend -n bouldy

            # Wait for rollout
            kubectl rollout status deployment/api -n bouldy --timeout=120s
            kubectl rollout status deployment/frontend -n bouldy --timeout=120s

            echo "✅ Deployed successfully"