"""add branding to chatbots

Revision ID: 22ee94bb2f76
Revises: 6c8a312ff3f9
Create Date: 2026-02-17 16:50:40.689001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ee94bb2f76'
down_revision: Union[str, None] = '6c8a312ff3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('accent_primary', sa.String(length=7), nullable=True))
    op.add_column('chatbots', sa.Column('accent_secondary', sa.String(length=7), nullable=True))
    op.add_column('chatbots', sa.Column('avatar_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbots', 'avatar_url')
    op.drop_column('chatbots', 'accent_secondary')
    op.drop_column('chatbots', 'accent_primary')
    # ### end Alembic commands ###
