"""upgrade evaluations table and add evaluation_results

Revision ID: 918b5b9ff283
Revises: 1ad51f8db60a
Create Date: 2026-02-28 03:46:00.179433

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '918b5b9ff283'
down_revision: Union[str, None] = '1ad51f8db60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
