"""add api_key to chatbots

Revision ID: c7d90fd2417b
Revises: ac1dea3b04dd
Create Date: 2026-02-13 12:17:00.550341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d90fd2417b'
down_revision: Union[str, None] = 'ac1dea3b04dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('llm_api_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbots', 'llm_api_key')
    # ### end Alembic commands ###
